const tips = {
  stres: "Stres adalah respons alami tubuh terhadap tekanan hidup, namun jika dibiarkan berlarut-larut, bisa berdampak serius pada kesehatan mental dan fisik. Untuk mengelola stres, penting untuk terlebih dahulu mengenali penyebabnya, apakah itu pekerjaan, hubungan, atau hal lain. Setelah itu, cobalah teknik relaksasi seperti pernapasan dalam, meditasi, atau yoga. Olahraga ringan seperti berjalan kaki 30 menit sehari juga terbukti efektif mengurangi hormon stres. Buat jadwal harian yang seimbang antara pekerjaan dan waktu istirahat. Jangan ragu mengambil jeda singkat saat merasa kewalahan. Menulis jurnal harian juga bisa membantu menuangkan emosi yang terpendam. Dan yang tak kalah penting, bicarakan perasaanmu dengan orang yang kamu percaya atau konselor, agar kamu tidak memendam semuanya sendiri.",
  Kecemasan: "Gangguan kecemasan membuat seseorang terus merasa khawatir berlebihan terhadap hal-hal yang mungkin tidak terlalu penting bagi orang lain. Untuk mengatasi hal ini, penting untuk melatih kesadaran diri melalui teknik mindfulness dan meditasi. Atur pola tidur dan makan secara teratur karena tubuh yang sehat mendukung pikiran yang tenang. Kurangi konsumsi kafein, alkohol, atau gula berlebih yang bisa memperburuk rasa cemas. Ketika pikiran mulai dipenuhi kekhawatiran, coba alihkan perhatian ke aktivitas yang kamu sukai, seperti menggambar, berkebun, atau mendengarkan musik yang menenangkan. Latih diri untuk berpikir rasional dengan mencatat kekhawatiran dan mencari bukti nyata yang mendukung atau menyangkalnya. Yang terpenting, jangan malu untuk meminta bantuan profesional bila kecemasan mulai mengganggu aktivitas harianmu.",
  hubungan: "Hubungan dalam keluarga atau pertemanan yang tidak sehat bisa menjadi sumber stres tersendiri. Untuk menjaga kesehatan mental dalam konteks ini, penting untuk membangun komunikasi terbuka yang disertai empati. Belajar mengatakan “tidak” adalah bentuk perlindungan diri yang sah, terutama jika kamu merasa batas pribadimu dilanggar. Latih kemampuan mendengarkan dan memahami, namun jangan sampai kamu sendiri kehilangan identitas atau kebutuhan emosionalmu. Jika ada konflik, cobalah selesaikan dengan pendekatan yang tenang dan bijaksana. Hindari menyimpan dendam karena itu bisa menggerogoti kesehatan mental secara perlahan. Jangan ragu mencari bantuan konseling keluarga atau hubungan bila situasi terasa semakin kompleks dan melelahkan.",
  Depresi: "Depresi bukan sekadar rasa sedih biasa; ini adalah kondisi serius yang membuat seseorang kehilangan minat, semangat, bahkan harapan. Untuk menghadapi depresi, cobalah untuk menjaga rutinitas meskipun terasa sulit. Bangun dan tidur pada jam yang sama setiap hari bisa membantu stabilkan suasana hati. Meskipun terasa berat, upayakan bergerak dan terlibat dalam aktivitas kecil seperti membersihkan kamar, menyiram tanaman, atau keluar rumah sebentar. Hindari menyendiri terlalu lama — jalin kontak dengan teman atau keluarga meski hanya lewat pesan. Menulis perasaan di jurnal bisa menjadi cara aman untuk menyalurkan emosi. Jika perasaan hampa atau putus asa terus muncul, pertimbangkan untuk berbicara dengan psikolog, karena terapi dan pengobatan bisa sangat membantu dalam proses pemulihan.",
  Trauma: "Trauma bisa muncul akibat pengalaman yang menyakitkan atau mengancam, seperti kekerasan, kehilangan orang tercinta, atau bencana. Untuk mulai menyembuhkan luka batin, pertama-tama akui bahwa perasaanmu valid dan kamu berhak merasakannya. Proses penyembuhan tidak harus cepat, jadi beri dirimu ruang dan waktu. Ekspresikan emosi melalui cara yang aman dan kreatif, seperti menulis, menggambar, atau musik. Hindari memaksa diri untuk “cepat pulih”, karena setiap orang memiliki prosesnya masing-masing. Cari lingkungan yang suportif dan aman, baik secara fisik maupun emosional. Jika kamu merasa terjebak dalam kilas balik, mimpi buruk, atau rasa takut berlebihan, bantuan profesional seperti terapi trauma bisa sangat membantu memulihkan kendali atas hidupmu.",
  Mood: "Gangguan mood seperti bipolar atau perubahan suasana hati ekstrem bisa mengganggu produktivitas dan hubungan. Untuk mengelolanya, penting untuk mengenali pola emosimu dengan mencatat perubahan suasana hati harian. Ini membantumu memahami pemicu dan ritme emosional. Tetapkan rutinitas yang stabil untuk tidur, makan, dan aktivitas harian, karena ketidakteraturan bisa memperburuk mood. Hindari alkohol dan zat-zat lain yang bisa memicu perubahan emosi drastis. Temukan cara menyalurkan energi positif melalui hobi atau olahraga ringan. Jika kamu sedang dalam fase “up” (mania), cobalah memperlambat langkah dan batasi pengambilan keputusan besar. Sebaliknya, jika sedang dalam fase “down” (depresi), cari dukungan sosial atau profesional. Terapi dan pengobatan rutin sangat disarankan untuk menjaga kestabilan jangka panjang."
};

function showTip(key) {
  const content = document.getElementById('tip-content');
  content.textContent = tips[key];
}
